package sensorNetwork;


/**
* sensorNetwork/SensorNetworkHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Thursday, March 26, 2015 8:27:10 PM GMT-03:00
*/

abstract public class SensorNetworkHelper
{
  private static String  _id = "IDL:sensorNetwork/SensorNetwork:1.0";

  public static void insert (org.omg.CORBA.Any a, sensorNetwork.SensorNetwork that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sensorNetwork.SensorNetwork extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sensorNetwork.SensorNetworkHelper.id (), "SensorNetwork");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sensorNetwork.SensorNetwork read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SensorNetworkStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sensorNetwork.SensorNetwork value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sensorNetwork.SensorNetwork narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sensorNetwork.SensorNetwork)
      return (sensorNetwork.SensorNetwork)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sensorNetwork._SensorNetworkStub stub = new sensorNetwork._SensorNetworkStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sensorNetwork.SensorNetwork unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sensorNetwork.SensorNetwork)
      return (sensorNetwork.SensorNetwork)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sensorNetwork._SensorNetworkStub stub = new sensorNetwork._SensorNetworkStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
