package sensorNetwork;


/**
* sensorNetwork/SensorsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Saturday, March 28, 2015 10:12:30 AM GMT-03:00
*/

abstract public class SensorsHelper
{
  private static String  _id = "IDL:sensorNetwork/Sensors:1.0";

  public static void insert (org.omg.CORBA.Any a, sensorNetwork.Sensor[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sensorNetwork.Sensor[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = sensorNetwork.SensorHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (sensorNetwork.SensorsHelper.id (), "Sensors", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sensorNetwork.Sensor[] read (org.omg.CORBA.portable.InputStream istream)
  {
    sensorNetwork.Sensor value[] = null;
    int _len0 = istream.read_long ();
    value = new sensorNetwork.Sensor[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = sensorNetwork.SensorHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sensorNetwork.Sensor[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      sensorNetwork.SensorHelper.write (ostream, value[_i0]);
  }

}
