package sensorNetwork;


/**
* sensorNetwork/SensorNetwork.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Saturday, March 28, 2015 10:12:30 AM GMT-03:00
*/

public interface SensorNetwork extends SensorNetworkOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SensorNetwork
