package sensorNetwork;


/**
* sensorNetwork/SensorNetwork.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Thursday, March 26, 2015 8:27:10 PM GMT-03:00
*/

public interface SensorNetwork extends SensorNetworkOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SensorNetwork
