package sensorNetwork;


/**
* sensorNetwork/SensorNetworkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Thursday, March 26, 2015 8:27:10 PM GMT-03:00
*/

public interface SensorNetworkOperations 
{
  void addSensorToNetwork (sensorNetwork.Sensor sensor);
  void deleteSensorFromNetwork (sensorNetwork.Sensor sensor);
  void updateTemperatureValueToSensor (sensorNetwork.Sensor sensor, int temperature);
  void updatePhValueToSensor (sensorNetwork.Sensor sensor, int temperature);
  void updateColorValueToSensor (sensorNetwork.Sensor sensor, int temperature);
  sensorNetwork.Sensor[] getSensors ();
  String getName ();
  void start ();
} // interface SensorNetworkOperations
