package sensorNetwork;


/**
* sensorNetwork/SensorNetworkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Saturday, March 28, 2015 10:12:30 AM GMT-03:00
*/

public interface SensorNetworkOperations 
{
  void addSensorToNetwork (sensorNetwork.Sensor sensor);
  void deleteSensorFromNetwork (sensorNetwork.Sensor sensor);
  void updateTemperatureValueToSensor (sensorNetwork.Sensor sensor, int temperature);
  void updatePhValueToSensor (sensorNetwork.Sensor sensor, int ph);
  void updateColorValueToSensor (sensorNetwork.Sensor sensor, int color);
  sensorNetwork.Sensor[] getSensors ();
} // interface SensorNetworkOperations
