package sensorNetwork;

/**
* sensorNetwork/SensorNetworkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorNetwork.idl
* Thursday, March 26, 2015 8:27:10 PM GMT-03:00
*/

public final class SensorNetworkHolder implements org.omg.CORBA.portable.Streamable
{
  public sensorNetwork.SensorNetwork value = null;

  public SensorNetworkHolder ()
  {
  }

  public SensorNetworkHolder (sensorNetwork.SensorNetwork initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sensorNetwork.SensorNetworkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sensorNetwork.SensorNetworkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sensorNetwork.SensorNetworkHelper.type ();
  }

}
